---
apiVersion: v2
name: lgtm-multi-tenant-proxy
description: Helm chart for Grafana Multi Tenant Proxy
type: application
appVersion: v0.9.5
version: 0.9.13
home: https://github.com/r-it-ae/lgtm-multi-tenant-proxy
sources:
  - https://github.com/r-it-ae/lgtm-multi-tenant-proxy
icon: https://s.giantswarm.io/app-icons/grafana/1/dark.svg
maintainers:
  - name: tcheksa62
    email: kopolk@gmail.com
  - name: r-it-ae
    email: r.ducamp+github@gmail.com
  # - name: giantswarm/team-atlas
  #   email: team-atlas@giantswarm.io
