# -- Overrides the chart's name
nameOverride: ""
# -- Overrides the chart's computed fullname
fullnameOverride: ""

enabled: true

global:
  image:
    # -- Overrides the Docker registry globally for all images
    registry: "ghcr.io"

proxy:
  # -- Number of replicas for the multi-tenant proxy
  replicas: 3

  autoscaling:
    # -- Enable autoscaling for the multi-tenant proxy
    enabled: true
    # -- Minimum autoscaling replicas for the multi-tenant proxy
    minReplicas: 2
    # -- Maximum autoscaling replicas for the multi-tenant proxy
    maxReplicas: 4
    # -- Target CPU utilisation percentage for the multi-tenant proxy
    targetCPUUtilizationPercentage: 90
    # -- Target memory utilisation percentage for the multi-tenant proxy
    targetMemoryUtilizationPercentage: 80

  image:
    # -- Repository to get multi-tenant proxy image from.
    repository: ronan-wescale/lgtm-multi-tenant-proxy
    # -- Overrides the image tag whose default is the chart's appVersion
    tag: ""
    # -- Overrides the image pull policy whose default is 'IfNotPresent'
    pullPolicy: IfNotPresent

  # -- List of target servers to proxy
  targetServers: []

  # -- Environment variables for the multi-tenant proxy
  # env: []

  # -- Resource requests and limits
  resources:
    limits:
      memory: 500Mi
    requests:
      memory: 50Mi
      cpu: 50m

  # -- Readiness probe configuration
  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 15
  
  ## - liveness probe configuration
  livenessProbe:
    httpGet:
      path: /health
      port: http

  #  -- Disable if credentials are provided externally
  deployCredentials: false

  # -- The credentials for the multi-tenant-proxy
  credentials: |-
    users:
      - username: Tenant1
        password: 1tnaneT
        orgid: tenant-1
      - username: Tenant2
        password: 2tnaneT
        orgid: tenant-2

  # -- The container SecurityContext for the multi-tenant-proxy container
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault

  # -- Default container port
  containerPort: 3501

configReloader:
  image:
    # -- Registry to get config reloader image from. Overrides global.image.registry.
    registry: "docker.io"
    # -- Repository to get config reloader image from.
    repository: giantswarm/configmap-reload
    # -- Tag of image to use for config reloading.
    tag: v0.15.0

  # -- Resource requests and limits to apply to the config reloader containers.
  resources:
    requests:
      cpu: "1m"
      memory: "5Mi"

  # -- Security context to apply to the config reloader containers.
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault

# -- The pod SecurityContext
podSecurityContext:
  fsGroup: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001
  seccompProfile:
    type: RuntimeDefault

service:
  ## -- Default service port
  port: 80

ingress:
  # -- Specifies whether an ingress for the multi-tenant-proxy should be created
  enabled: false
  # -- Ingress Class Name. MAY be required for Kubernetes versions >= 1.18
  ingressClassName: ""
  # -- Annotations for the gateway ingress
  annotations: {}
  # -- Labels for the gateway ingress
  labels: {}
  # -- Hosts configuration for the multi-tenant-proxy ingress, passed through the `tpl` function to allow templating
  hosts:
    - host: multi-tenant-proxy.loki.example.com
      paths:
        - path: /
          # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.) might also be required by some Ingress Controllers
          # pathType: Prefix
  # -- TLS configuration for the gateway ingress. Hosts passed through the `tpl` function to allow templating
  tls:
    - secretName: loki-multi-tenant-proxy-tls
      hosts:
        - write.multi-tenant-proxy.loki.example.com

networkPolicy:
  # -- Specifies whether the multi-tenant proxy should be deployed with a network policy
  enabled: true
  # -- Specifies the flavor of network policy to use
  flavor: cilium

monitoring:
  enabled: true
